# Generated by Django 6.0.2 on 2026-02-15 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverassignment',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_assignments', to='routes.route'),
        ),
        migrations.AlterUniqueTogether(
            name='driverassignment',
            unique_together={('driver', 'route', 'bus', 'is_active')},
        ),
    ]
